# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Andi/GIT/Embedded Systems/Embedded-Systems-Labs/Lab4/Lab4.srcs/sources_1/bd/Hello_World/ip/Hello_World_axi_gpio_0_0/Hello_World_axi_gpio_0_0.xci
# IP: The module: 'Hello_World_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Andi/GIT/Embedded Systems/Embedded-Systems-Labs/Lab4/Lab4.gen/sources_1/bd/Hello_World/ip/Hello_World_axi_gpio_0_0/Hello_World_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Hello_World_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Andi/GIT/Embedded Systems/Embedded-Systems-Labs/Lab4/Lab4.gen/sources_1/bd/Hello_World/ip/Hello_World_axi_gpio_0_0/Hello_World_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Hello_World_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Andi/GIT/Embedded Systems/Embedded-Systems-Labs/Lab4/Lab4.gen/sources_1/bd/Hello_World/ip/Hello_World_axi_gpio_0_0/Hello_World_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Hello_World_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/Andi/GIT/Embedded Systems/Embedded-Systems-Labs/Lab4/Lab4.srcs/sources_1/bd/Hello_World/ip/Hello_World_axi_gpio_0_0/Hello_World_axi_gpio_0_0.xci
# IP: The module: 'Hello_World_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Andi/GIT/Embedded Systems/Embedded-Systems-Labs/Lab4/Lab4.gen/sources_1/bd/Hello_World/ip/Hello_World_axi_gpio_0_0/Hello_World_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Hello_World_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Andi/GIT/Embedded Systems/Embedded-Systems-Labs/Lab4/Lab4.gen/sources_1/bd/Hello_World/ip/Hello_World_axi_gpio_0_0/Hello_World_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Hello_World_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Andi/GIT/Embedded Systems/Embedded-Systems-Labs/Lab4/Lab4.gen/sources_1/bd/Hello_World/ip/Hello_World_axi_gpio_0_0/Hello_World_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Hello_World_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
