# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/Hello_World/Hello_World.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Hello_World || ORIG_REF_NAME==Hello_World} -quiet] -quiet

# IP: bd/Hello_World/ip/Hello_World_microblaze_0_0/Hello_World_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Hello_World_microblaze_0_0 || ORIG_REF_NAME==Hello_World_microblaze_0_0} -quiet] -quiet

# IP: bd/Hello_World/ip/Hello_World_axi_gpio_0_0/Hello_World_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Hello_World_axi_gpio_0_0 || ORIG_REF_NAME==Hello_World_axi_gpio_0_0} -quiet] -quiet

# IP: bd/Hello_World/ip/Hello_World_clk_wiz_0_0/Hello_World_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Hello_World_clk_wiz_0_0 || ORIG_REF_NAME==Hello_World_clk_wiz_0_0} -quiet] -quiet

# IP: bd/Hello_World/ip/Hello_World_dlmb_v10_0/Hello_World_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Hello_World_dlmb_v10_0 || ORIG_REF_NAME==Hello_World_dlmb_v10_0} -quiet] -quiet

# IP: bd/Hello_World/ip/Hello_World_ilmb_v10_0/Hello_World_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Hello_World_ilmb_v10_0 || ORIG_REF_NAME==Hello_World_ilmb_v10_0} -quiet] -quiet

# IP: bd/Hello_World/ip/Hello_World_dlmb_bram_if_cntlr_0/Hello_World_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Hello_World_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==Hello_World_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/Hello_World/ip/Hello_World_ilmb_bram_if_cntlr_0/Hello_World_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Hello_World_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==Hello_World_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/Hello_World/ip/Hello_World_lmb_bram_0/Hello_World_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Hello_World_lmb_bram_0 || ORIG_REF_NAME==Hello_World_lmb_bram_0} -quiet] -quiet

# IP: bd/Hello_World/ip/Hello_World_mdm_1_0/Hello_World_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Hello_World_mdm_1_0 || ORIG_REF_NAME==Hello_World_mdm_1_0} -quiet] -quiet

# IP: bd/Hello_World/ip/Hello_World_rst_clk_wiz_0_100M_0/Hello_World_rst_clk_wiz_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Hello_World_rst_clk_wiz_0_100M_0 || ORIG_REF_NAME==Hello_World_rst_clk_wiz_0_100M_0} -quiet] -quiet

# IP: bd/Hello_World/ip/Hello_World_axi_uartlite_0_0/Hello_World_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Hello_World_axi_uartlite_0_0 || ORIG_REF_NAME==Hello_World_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/Hello_World/ip/Hello_World_xbar_0/Hello_World_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Hello_World_xbar_0 || ORIG_REF_NAME==Hello_World_xbar_0} -quiet] -quiet

# IP: bd/Hello_World/ip/Hello_World_microblaze_0_axi_periph_0/Hello_World_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Hello_World_microblaze_0_axi_periph_0 || ORIG_REF_NAME==Hello_World_microblaze_0_axi_periph_0} -quiet] -quiet

# XDC: c:/Users/Andi/GIT/Embedded Systems/Embedded-Systems-Labs/Lab4/Lab4.gen/sources_1/bd/Hello_World/Hello_World_ooc.xdc
